questions = [
   "What made you switch from your prior career into programming?",
   "How do you familiarize yourself with a codebase you haven't worked in before?",
   "Describe to me the steps you would take to build out a product.",
   "Tell me how you solve a problem.",
   "Describe your background. How did you get to where you are now? What was your previous career field. What did you like about it? What didn't you like about it? Why coding?",
   "Describe your time at Turing. What worked for you? What didn't work for you? What was the structure of the program?",
   "Describe your teamwork experience in a coding environment. How big of a team did you work with?",
   "A lot of this job will be full-stack. Your experience is largely __ (Back End, Front End). How do you feel like you'd be able to contribute to the team with only that experience? How comfortable are you with getting uncomfortable with a new language?",
   "Describe your coding experience and why you wish to continue?",
   "What are you looking for in a company, and why would you want to work here?",
   "Describe an example of how you have handled a stressful situation.",
   "Have you ever had to switch gears in the middle of a project to get something fixed immediately?, How did you react?",
   "What is your 100% ideal role for your first web development job?",
   "Tell me about a time you had a disagreement with a colleague and how you resolved it.",
   "What project of yours are you most proud of and why?",
   "Explain one of the most difficult code problems you've had to solve, either on your own authored code, or in contributing to someone else's.",
   "Describe a time when you received feedback that you were surprised by. What did you do with that feedback?",
   "Describe a successful idea or project you worked on. What are some of the challenges you had to overcome and What made it a success?",
   "Describe a project that failed, a project you had to give up on or a time you worked really hard on a project and it just didn't pan out as expected. What happened and How did you make the decisions that you made?",
   "What is your approach to working on a team?",
   "What is an area of growth for you?",
   "Describe your strengths. How have you seen these in practice as a developer?",
   "What is something that your hobbies or interests tell me about you that your resume cannot?",
   "Tell me about a time you failed. How did you deal with the situation?",
   "Give me an example of a time you were able to be creative with your work. What was exciting or difficult about it?",
   "Sometimes it's just not possible to get everything on your to-do list done. Tell me about a time your responsibilities got a little overwhelming. What did you do?",
   "Tell me about a time you set a goal for yourself. How did you go about ensuring that you would meet your objective?",
   "Tell me about a time when you had to rely on written communication to get your ideas across to your team.",
   "Tell me about a successful presentation you gave and why you think it was a hit.",
   "Describe a long-term project that you managed. How did you keep everything moving along in a timely manner?",
   "Describe a time when you saw some problem and took the initiative to correct it rather than waiting for someone else to do it.",
   "Tell me about a time when you worked under close supervision or extremely loose supervision. How did you handle that?",
   "Tell me about a time you needed to get information from someone who wasn't very responsive. What did you do?",
]

puts questions.sample